#include <bitset>
#include <functional>
#include <utility>
#include <ctime>
#include <chrono>
#include <tuple>
#include <new>
#include <memory>
#include <cstdint>
#include <limits>
#include <cassert>
#include <string>
#include <array>
#include <vector>
#include <deque>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>
#include <stack>
#include <queue>
#include <algorithm>
#include <iostream>
#include <fstream>
#include <sstream>
#include <strstream>